name: 'Docker Build and Push'
description: 'Build and push Docker image to ECR'

inputs:
  aws_role_arn:
    description: 'AWS OIDC role ARN'
    required: true
  aws_region:
    description: 'AWS region'
    required: false
    default: 'eu-west-1'
  ecr_repository:
    description: 'ECR repository name'
    required: false
    default: 'bitcoind'
  dockerfile_path:
    description: 'Path to Dockerfile'
    required: false
    default: 'Dockerfile'
  context_path:
    description: 'Build context path'
    required: false
    default: '.'

outputs:
  image_tag:
    description: 'Image tag (SHA)'
    value: ${{ steps.meta.outputs.version }}
  image_uri:
    description: 'Full image URI'
    value: ${{ steps.login-ecr.outputs.registry }}/${{ inputs.ecr_repository }}:${{ steps.meta.outputs.version }}

runs:
  using: 'composite'
  steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ inputs.aws_role_arn }}
        aws-region: ${{ inputs.aws_region }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ steps.login-ecr.outputs.registry }}/${{ inputs.ecr_repository }}
        tags: |
          type=sha,prefix=
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: ${{ inputs.context_path }}
        file: ${{ inputs.dockerfile_path }}
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
